//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package math

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/modules/ds/include
#cgo CFLAGS: -I${SRCDIR}/modules/stats/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/third_party/gmp
#cgo CFLAGS: -I${SRCDIR}/modules/platform/third_party/mpfr/src
#cgo CFLAGS: -I${SRCDIR}/math-c
#cgo CFLAGS: -I${SRCDIR}/modules/platform/src -O2 -Wall -std=c11 -mavx2 -mfma
#cgo linux CFLAGS: -D_POSIX_C_SOURCE=200112L
#cgo linux LDFLAGS: ${SRCDIR}/modules/platform/build/linux_amd64/libfinkit_platform_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_arm64/libfinkit_platform_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/platform/build/darwin_x86_64/libfinkit_platform_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/platform/build/windows_amd64/libfinkit_platform_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/ds/build/linux_amd64/libfinkit_ds_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/ds/build/darwin_arm64/libfinkit_ds_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/ds/build/darwin_x86_64/libfinkit_ds_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/ds/build/windows_amd64/libfinkit_ds_static.a -lm

#cgo linux LDFLAGS: ${SRCDIR}/modules/stats/build/linux_amd64/libfinkit_stats_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/stats/build/darwin_arm64/libfinkit_stats_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/stats/build/darwin_x86_64/libfinkit_stats_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/stats/build/windows_amd64/libfinkit_stats_static.a -lm

#include "cumsum.h"
#include "cummax.h"

// Platform sources (dependency)
#include "simd_detect.c"
#include "fc_bignum_init.c"
#include "fc_bigint.c"
#include "fc_bigfloat.c"
#include "fc_precision.c"
#include "mem_aligned.c"
#include "error.c"
#include "fc_init.c"

// Platform-specific sources
#if defined(__linux__)
  #include "modules/platform/src/platform_linux.c"
#elif defined(__APPLE__)
  #include "modules/platform/src/platform_macos.c"
#elif defined(_WIN32)
  #include "modules/platform/src/platform_win.c"
#endif

// math sources
#include "math-c/cumsum.c"
#include "math-c/cummax.c"
*/
import "C"

func init() {
	C.fc_init()
}
